FROM mongo:latest
# MongoDB Dockerfile

# Use the official MongoDB image from Docker Hub
# RUN apt-get update && apt-get install -y mongodb-clients

# Expose MongoDB port
EXPOSE 27017

CMD ["mongod"]
# RUN show dbs
# Start MongoDB service

# Insert initial data into MongoDB
# RUN mongosh --eval ' \
#     db.users.insertMany([ \
#         { "name": "JEET", "age": 35 }, \
#         { "name": "Dhairya", "age": 24 } \
#     ]); \
# '
